src/Entity/Stock.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\StockRepository")
 */
class Stock
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $symbol;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $price = null;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $refreshedAt = null;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Trade", mappedBy="stock")
     */
    private $trades;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $stockType;

    /**
     * @ORM\Column(type="float", nullable=true)
     */
    private $longTarget;

    /**
     * @ORM\Column(type="float", nullable=true)
     */
    private $shortTarget;

    /**
     * @ORM\Column(type="float", nullable=true)
     */
    private $callTarget;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $nextEarningsAt;

    /**
     * @ORM\OneToMany(targetEntity="Transaction", mappedBy="stock")
     */
    private $transactions;

    /**
     * @ORM\Column(type="boolean")
     */
    private $isWatchlistLong;

    /**
     * @ORM\Column(type="boolean")
     */
    private $isWatchlistShort;

    public function __construct()
    {
        $this->trades = new ArrayCollection();
        $this->transactions = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getSymbol(): ?string
    {
        return $this->symbol;
    }

    public function setSymbol(string $symbol): self
    {
        $this->symbol = $symbol;

        return $this;
    }

    public function getPrice(): ?string
    {
        return $this->price;
    }

    public function setPrice(string $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getRefreshedAt(): ?\DateTimeInterface
    {
        return $this->refreshedAt;
    }

    public function setRefreshedAt(\DateTimeInterface $refreshedAt): self
    {
        $this->refreshedAt = $refreshedAt;

        return $this;
    }

    /**
     * @return Collection|Trade[]
     */
    public function getTrades($type = null, $orderBy = null): Collection
    {
        $trades = $this->trades;

        if ($orderBy) {
            $orderByField   = isset($orderBy[0]) && $orderBy[0] ? $orderBy[0] : 'executedAt';
            $orderByDir     = isset($orderBy[1]) && $orderBy[1] != 'ASC' ? -1 : 1;

            $iterator = $this->trades->getIterator();
            $iterator->uasort(function ($a, $b) use ($orderByField, $orderByDir) {
                return call_user_func([$a, 'get'.$orderByField]) < call_user_func([$b, 'get'.$orderByField]) ? !$orderByDir : $orderByDir;
            });

            $trades = new ArrayCollection(iterator_to_array($iterator));
        }

        if ($type) {
            return $trades->filter(function($trade) use ($type) {
                return $trade->getTradeType() == $type;
            });
        }

        return $trades;
    }

    public function addTrade(Trade $trade): self
    {
        if (!$this->trades->contains($trade)) {
            $this->trades[] = $trade;
            $trade->setStock($this);
        }

        return $this;
    }

    public function removeTrade(Trade $trade): self
    {
        if ($this->trades->contains($trade)) {
            $this->trades->removeElement($trade);
            // set the owning side to null (unless already changed)
            if ($trade->getStock() === $this) {
                $trade->setStock(null);
            }
        }

        return $this;
    }

    public function getQuantity($tradeType) {
        $quantity = 0;

        foreach ($this->getTrades() as $trade) {
            if ($trade->getTradeType() == $tradeType) {
                $quantity += ($trade->getOrderType() == "Sell" || $trade->getOrderType() == "Expired") ? -$trade->getQuantity() : $trade->getQuantity();
            }
        }

        return $quantity;
    }

    public function getAdjustedPrice($tradeType) {
        $trades = $this->getTrades();

        /** @var Trade $oldest */
        $newest = $trades->first();

        foreach ($trades as $trade) {
            if ($trade->getTradeType() == $tradeType) {
                if ($trade->getExecutedAt() > $newest->getExecutedAt()) {
                    $newest = $trade;
                }
            }
        }

        return $newest->getAdjustedPrice();
    }

    public function getGain($tradeType) {
        if ($this->getPrice() <= 0) {
            $gain = 0;
        } elseif ($tradeType == 'Long' && $this->getAdjustedPrice('Long')) {
            $gain = (($this->getPrice() /$this->getAdjustedPrice('Long')) -1) *100;
        } elseif ($tradeType == 'Short' && $this->getAdjustedPrice('Short')) {
            $gain = (1- ($this->getPrice() /$this->getAdjustedPrice('Short'))) *100;
        } elseif ($tradeType == 'Option' && $this->getAdjustedPrice('Option')) {
            $gain = (($this->getPrice() /$this->getAdjustedPrice('Option')) -1) *100;
        } else {
            $gain = 0;
        }

        return round($gain,2);
    }

    public function getSoldProfit($type) {
        $profit = 0;

        $trades = $this->getTrades($type);

        $filteredTrades = $trades->filter(function($trade) {
            return ($trade->getOrderType() == 'Sell' || $trade->getOrderType() == 'Expired');
        });

        /** @var $filteredTrades Trade[] $filteredTrade */
        foreach ($filteredTrades as $filteredTrade) {
            $difference = ($filteredTrade->getTradeType() == 'Short') ? ($filteredTrade->getAdjustedPrice() -$filteredTrade->getPrice()) : ($filteredTrade->getPrice() -$filteredTrade->getAdjustedPrice());

            $profit += $filteredTrade->getQuantity() *($filteredTrade->getTradeType() == 'Option' ? 100 : 1) *$difference;
        }

        return $profit;
    }

    public function getStockType(): ?string
    {
        return $this->stockType;
    }

    public function setStockType(string $stockType): self
    {
        $this->stockType = $stockType;

        return $this;
    }

    public function getLongTarget(): ?float
    {
        return $this->longTarget;
    }

    public function setLongTarget(?float $longTarget): self
    {
        $this->longTarget = $longTarget;

        return $this;
    }

    public function getShortTarget(): ?float
    {
        return $this->shortTarget;
    }

    public function setShortTarget(?float $shortTarget): self
    {
        $this->shortTarget = $shortTarget;

        return $this;
    }

    public function getCallTarget(): ?float
    {
        return $this->callTarget;
    }

    public function setCallTarget(?float $callTarget): self
    {
        $this->callTarget = $callTarget;

        return $this;
    }

    public function getNextEarningsAt(): ?\DateTimeInterface
    {
        return $this->nextEarningsAt;
    }

    public function setNextEarningsAt(?\DateTimeInterface $nextEarningsAt): self
    {
        $this->nextEarningsAt = $nextEarningsAt;

        return $this;
    }

    /**
     * @return Collection|Transaction[]
     */
    public function getTransactions(): Collection
    {
        return $this->transactions;
    }

    public function addTransaction(Transaction $transaction): self
    {
        if (!$this->transactions->contains($transaction)) {
            $this->transactions[] = $transaction;
            $transaction->setStock($this);
        }

        return $this;
    }

    public function removeTransaction(Transaction $transaction): self
    {
        if ($this->transactions->contains($transaction)) {
            $this->transactions->removeElement($transaction);
            // set the owning side to null (unless already changed)
            if ($transaction->getStock() === $this) {
                $transaction->setStock(null);
            }
        }

        return $this;
    }

    public function isWatchlistLong(): ?bool
    {
        return $this->isWatchlistLong;
    }

    public function setWatchlistLong(bool $isWatchlistLong): self
    {
        $this->isWatchlistLong = $isWatchlistLong;

        return $this;
    }

    public function isWatchlistShort(): ?bool
    {
        return $this->isWatchlistShort;
    }

    public function setWatchlistShort(bool $isWatchlistShort): self
    {
        $this->isWatchlistShort = $isWatchlistShort;

        return $this;
    }

}

src/Entity/Trade.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\TradeRepository")
 */
class Trade
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="integer")
     */
    private $quantity;

    /**
     * @ORM\Column(type="float")
     */
    private $price;

    /**
     * @ORM\Column(type="float")
     */
    private $fee;

    /**
     * @ORM\Column(type="float")
     */
    private $total;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $trade_type;

    /**
     * @var \DateTimeInterface
     * @ORM\Column(type="datetime")
     */
    protected $createdAt;

    /**
     * @var \DateTimeInterface
     * @ORM\Column(type="datetime")
     */
    protected $updatedAt;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $description;

    /**
     * @ORM\Column(type="float")
     */
    private $adjusted_price;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $orderType;

    /**
     * @ORM\Column(type="datetime")
     */
    private $executedAt;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Stock", inversedBy="trades")
     */
    private $stock;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getQuantity(): ?int
    {
        return $this->quantity;
    }

    public function setQuantity(int $quantity): self
    {
        $this->quantity = $quantity;

        return $this;
    }

    public function getPrice(): ?float
    {
        return $this->price;
    }

    public function setPrice(float $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getFee(): ?float
    {
        return $this->fee;
    }

    public function setFee(float $fee): self
    {
        $this->fee = $fee;

        return $this;
    }

    public function getTotal(): ?float
    {
        return $this->total;
    }

    public function setTotal(float $total): self
    {
        $this->total = $total;

        return $this;
    }

    public function getTradeType(): ?string
    {
        return $this->trade_type;
    }

    public function setTradeType(string $trade_type): self
    {
        $this->trade_type = $trade_type;

        return $this;
    }

    public function getCreatedAt(): \DateTimeInterface
    {
        return $this->createdAt;
    }

    public function getUpdatedAt(): \DateTimeInterface
    {
        return $this->updatedAt;
    }

    public function setCreatedAt(\DateTimeInterface $createdAt): void
    {
        $this->createdAt = $createdAt;
    }

    public function setUpdatedAt(\DateTimeInterface $updatedAt): void
    {
        $this->updatedAt = $updatedAt;
    }

    /**
     * Updates createdAt and updatedAt timestamps.
     */
    public function updateTimestamps(): void
    {
        // Create a datetime with microseconds
        $dateTime = \DateTime::createFromFormat('U.u', sprintf('%.6F', microtime(true)));

        $dateTime->setTimezone(new \DateTimeZone(date_default_timezone_get()));

        if ($this->createdAt === null) {
            $this->createdAt = $dateTime;
        }

        $this->updatedAt = $dateTime;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getAdjustedPrice(): ?float
    {
        return $this->adjusted_price;
    }

    public function setAdjustedPrice(float $adjusted_price): self
    {
        $this->adjusted_price = $adjusted_price;

        return $this;
    }

    public function getOrderType(): ?string
    {
        return $this->orderType;
    }

    public function setOrderType(string $orderType): self
    {
        $this->orderType = $orderType;

        return $this;
    }

    public function getExecutedAt(): ?\DateTimeInterface
    {
        return $this->executedAt;
    }

    public function setExecutedAt(\DateTimeInterface $executedAt): self
    {
        $this->executedAt = $executedAt;

        return $this;
    }

    public function getStock(): ?Stock
    {
        return $this->stock;
    }

    public function setStock(?Stock $stock): self
    {
        $this->stock = $stock;

        return $this;
    }
}

templates/default/_chart.html.twig
<label for="chartSelect" class="btn btn-default btn-sm" data-toggle="tooltip" data-placement="top" title="Toggle chart visibility">
    <input id="chartSelect" type="checkbox" class="hidden">
    <i class="fa fa-pie-chart"></i> Chart
</label>

<div id="chart-container">
    <div id="chart"></div>
    <p></p>
    <div id="chartbar">
        <i class="fa fa-cube active clickable toolti" title="3D Pie Chart" data-toggle="tooltip" data-placement="top"></i>
        <i class="fa fa-pie-chart clickable" title="Pie Chart" data-toggle="tooltip" data-placement="top"></i>
        <i class="fa fa-line-chart clickable" title="Line Graph" data-toggle="tooltip" data-placement="top"></i>
        <i class="fa fa-area-chart clickable" title="Area Graph" data-toggle="tooltip" data-placement="top"></i>
        <i class="fa fa-bar-chart clickable" title="Vertical Bar Chart" data-toggle="tooltip" data-placement="top"></i>
        <i class="fa fa-tasks fa-rotate-90 clickable" title="Stacking Vertical Bar Chart" data-toggle="tooltip" data-placement="top"></i>
        <i class="fa fa-align-left clickable" title="Horizontal Bar Chart" data-toggle="tooltip" data-placement="top"></i>
        <i class="fa fa-tasks fa-rotate-180 clickable" title="Stacking Horizontal Bar Chart" data-toggle="tooltip" data-placement="top"></i>
    </div>
    <p></p>
</div>

templates/default/detail.html.twig
{% extends 'base.html.twig' %}

{% form_theme form 'bootstrap_4_layout.html.twig' %}

{% block extranav %}
{% endblock %}

{% block content %}
    <h1>Detailed data for {{ symbol }}</h1>

    <table class="table table-striped">
        <thead>
        <tr>
            <th>Date</th>
            <th>Quantity</th>
            <th>Trade type</th>
            <th>Trade price</th>
            <th>Adjusted price</th>
        </tr>
        </thead>
        <tbody>
    {% for trade in stock.trades(tradeType, [ 'executedAt', 'DESC' ]) %}
        <tr>
            <td>{{ trade.executedAt|date('jS M \'y') }}</td>
            <td>{{ trade.quantity }}</td>
            <td>{{ trade.tradeType }}</td>
            <td>${{ trade.price|round(2) }}</td>
            <td>${{ trade.adjustedPrice|round(2) }}</td>
        </tr>
    {% endfor %}
        </tbody>
    </table>

    {{ form_start(form) }}
    <div class="form-group">
        <label for="targetGainCalc">Target gain</label>
        <input type="number" step="0.01" id="targetGainCalc" class="form-control" data-buyprice="{{ stock.adjustedPrice(tradeType) }}" />
    </div>
    {{ form_rest(form) }}
    {{ form_end(form) }}
{% endblock %}

templates/default/view.html.twig
{% extends 'base.html.twig' %}

{% block content %}
    {% include 'default/_chart.html.twig' %}

    {% for isWatchlist in [0, 1] %}
        {% if not isWatchlist %}
            <h1>{{ tradeType }} trades</h1>
        {% else %}
            <h1>Watchlist</h1>
        {% endif %}

        <table class="table table-striped trade-data {% if not isWatchlist %}data-sortable{% endif %}">
            {% if not isWatchlist %}
            <thead>
            <tr>
                <th>Symbol</th>
                <th>Quantity</th>
                <th>Traded price</th>
                <th>Traded value</th>
                <th>Current price</th>
                <th>Current value</th>
                <th>Profit</th>
                <th>Gain</th>
                <th>10% price</th>
                <th>10% profit</th>
                <th>Target price</th>
                <th>Target profit</th>
                <th>Target gain</th>
                {% if tradeType == 'Long' %}
                    <th>Next earnings call</th>
                {% endif %}
            </tr>
            </thead>
            {% endif %}

            {% set total_quantity       = 0 %}
            {% set total_invested       = 0 %}
            {% set total_value          = 0 %}
            {% set total_gain           = 0 %}
            {% set total_tenValue       = 0 %}
            {% set total_targetValue    = 0 %}

            <tbody>
            {% for stock in stocks %}
                {% set showActive = stock.quantity(tradeType) and not isWatchlist %}
                {% set showWatchlist = not stock.quantity(tradeType) and isWatchlist and ((tradeType == 'Long' and stock.watchlistLong) or (tradeType == 'Call' and stock.watchlistCall) or (tradeType == 'Short' and stock.watchlistShort)) %}

                {% if showActive or showWatchlist %}
                    {% set stock__quantity              = stock.quantity(tradeType) %}
                    {% set stock__tradedPrice           = stock.adjustedPrice(tradeType) %}
                    {% set stock__tradedValue           = stock__tradedPrice *stock__quantity *(tradeType == 'Option' ? 100 : 1) %}
                    {% set stock__currentPrice          = stock.price %}
                    {% set stock__currentValue          = stock__currentPrice *stock__quantity *(tradeType == 'Option' ? 100 : 1) %}

                    {% if tradeType == 'Short' %}
                        {% set stock__position              = stock__quantity *(tradeType == 'Option' ? 100 : 1) *(stock__tradedPrice -stock__currentPrice) %}
                    {% else %}
                        {% set stock__position              = stock__quantity *(tradeType == 'Option' ? 100 : 1) *(stock__currentPrice -stock__tradedPrice) %}
                    {% endif %}

                    {% if tradeType == 'Short' %}
                        {% set stock__targetPrice       = stock.shortTarget ? stock.shortTarget : 0 %}
                    {% elseif tradeType == 'Option' %}
                        {% set stock__targetPrice       = stock.callTarget ? stock.callTarget : 0 %}
                    {% else %}
                        {% set stock__targetPrice       = stock.longTarget ? stock.longTarget : 0 %}
                    {% endif %}

                    {% if tradeType == 'Short' %}
                        {% set stock__targetPriceDiff   = stock__tradedPrice -stock__targetPrice %}
                        {% set stock__targetPriceRatio  = stock__targetPrice ? 1 -(stock__targetPrice /stock__tradedPrice) : 1 %}
                    {% else %}
                        {% set stock__targetPriceDiff   = stock__targetPrice -stock__tradedPrice %}
                        {% set stock__targetPriceRatio  = stock__tradedPrice ? (stock__targetPrice /stock__tradedPrice) -1 : 1 %}
                    {% endif %}

                    {% set stock__targetValue           = stock__targetPriceDiff *stock__quantity *(tradeType == 'Option' ? 100 : 1) %}

                    {% if tradeType == 'Short' %}
                        {% set stock__targetGain        = stock__tradedPrice and stock__targetPrice ? (stock__targetPriceRatio *100) : 0 %}
                    {% else %}
                        {% set stock__targetGain        = stock__tradedPrice and stock__targetPrice ? (stock__targetPriceRatio *100) : 0 %}
                    {% endif %}

                    {% if tradeType == 'Short' %}
                        {% set stock__tenPrice          = stock__tradedPrice *0.9 %}
                        {% set stock__tenPriceDiff      = stock__tradedPrice -stock__tenPrice %}
                        {% set stock__tenPriceRatio     = stock__tenPrice ? (stock__tradedPrice /stock__tenPrice) -1 : 1 %}
                    {% else %}
                        {% set stock__tenPrice          = stock__tradedPrice *1.1 %}
                        {% set stock__tenPriceDiff      = stock__tenPrice -stock__tradedPrice %}
                        {% set stock__tenPriceRatio     = stock__tradedPrice ? (stock__tenPrice /stock__tradedPrice) -1 : 1 %}
                    {% endif %}
                    {% set stock__tenValue              = stock__tenPriceDiff *stock__quantity *(tradeType == 'Option' ? 100 : 1) %}
                    {% set stock__tenGain               = stock__tenPrice and stock__tenPrice ? (stock__tenPriceRatio *100) : 0 %}


                    {% if tradeType == 'Short' %}
                        {% set highlight_targetPrice    = stock__targetPrice and (stock__targetPrice -stock__currentPrice) > 0 %}
                        {% set highlight_tenPrice       = stock__tenPrice and (stock__tenPrice -stock__currentPrice) > 0 %}
                    {% else %}
                        {% set highlight_targetPrice    = stock__targetPrice and (stock__currentPrice -stock__targetPrice) > 0 %}
                        {% set highlight_tenPrice       = stock__tenPrice and (stock__currentPrice -stock__tenPrice) > 0 %}
                    {% endif %}
                    {% set highlight_currentPrice       = highlight_targetPrice or highlight_tenPrice %}
                    {% set highlight_earnings           = stock.nextEarningsAt and stock.nextEarningsAt|timeAgo == 'Today' %}
                    {% set highlight_earnings_old       = stock.nextEarningsAt and 'ago' in stock.nextEarningsAt|timeAgo  %}

                    {% set total_quantity               = total_quantity +stock__quantity %}
                    {% set total_invested               = total_invested +stock__tradedValue %}
                    {% set total_value                  = total_value +stock__currentValue %}
                    {% if tradeType == 'Short' %}
                        {% set total_priceRatio         = total_value ? 1 -(total_invested /total_value) : 1 %}
                        {% set total_gain               = total_priceRatio *100 %}
                    {% else %}
                        {% set total_priceRatio         = total_value ? (total_value /total_invested) -1 : 1 %}
                        {% set total_gain               = total_priceRatio *100 %}
                    {% endif %}
                    {% set total_tenValue               = total_tenValue +stock__tenValue %}
                    {% set total_targetValue            = total_targetValue +stock__targetValue %}

                    <tr>
                        <td class="text"><a href="{{ url(detailRoute, { 'symbol': stock.symbol }) }}">{{ stock.symbol }}</a> [<a target="_blank" href="https://www.investopedia.com/markets/quote?tvwidgetsymbol={{ stock.symbol }}">chart</a>]</td>
                        <td class="number">{{ stock__quantity }}</td>
                        <td class="money">{{ stock__tradedPrice|round(2)|number_format(2) }}</td>
                        <td class="money">{{ stock__tradedValue|round(2)|number_format(2) }}</td>
                        <td class="money{% if highlight_currentPrice %} highlight{% endif %}">{{ stock__currentPrice|round(2)|number_format(2) }}</td>
                        <td class="money">{{ stock__currentValue|round(2)|number_format(2) }}</td>
                        <td class="money{% if stock.gain(tradeType) > 0 %} up{% elseif (stock.gain(tradeType) < 0) %} down{% endif %}">{{ stock__position|number_format(2) }}</td>
                        <td class="ratio{% if stock.gain(tradeType) > 0 %} up{% elseif (stock.gain(tradeType) < 0) %} down{% endif %}">{{ stock.gain(tradeType)|number_format(2) }}%</td>
                        <td class="money{% if highlight_tenPrice %} highlight{% endif %}">{{ stock__tenPrice|round(2)|number_format(2) }}</td>
                        <td class="money">
                            {% if stock__tenValue %}
                                {{ stock__tenValue|round(2)|number_format(2) }}
                            {% else %}
                                -
                            {% endif %}
                        </td>
                        <td class="money{% if highlight_targetPrice %} highlight{% endif %}">
                            {% if stock__targetPrice %}
                                {{ stock__targetPrice|round(2)|number_format(2) }}
                            {% else %}
                                -
                            {% endif %}
                        </td>
                        <td class="money">
                            {% if stock__targetValue %}
                                {{ stock__targetValue|round(2)|number_format(2) }}
                            {% else %}
                                -
                            {% endif %}
                        </td>
                        <td class="ratio">
                            {% if stock__targetGain %}
                                {{ stock__targetGain|round(2) }}%
                            {% else %}
                                -
                            {% endif %}
                        </td>
                        {% if tradeType == 'Long' or tradeType == 'Short' %}
                        <td class="text{% if highlight_earnings %} highlight{% elseif highlight_earnings_old %} highlight-old{% endif %}">
                            {% if stock.nextEarningsAt %}
                                {{ stock.nextEarningsAt|timeAgo }}
                            {% else %}
                                -
                            {% endif %}
                        </td>
                        {% endif %}
                    </tr>
                {% endif %}
            {% endfor %}
            </tbody>

            {% if not isWatchlist %}
            <tfoot>
            <tr>
                <td class="text">Totals:</td>
                <td class="number">{{ total_quantity }}</td>
                <td class="text"></td>
                <td class="money">{{ total_invested|number_format(2) }}</td>
                <td class="text"></td>
                <td class="money">{{ total_value|round(2)|number_format(2) }}</td>
                <td class="money{% if total_gain > 0 %} up{% elseif (total_gain < 0) %} down{% endif %}">{{ (total_value -total_invested)|round(2)|number_format(2) }}</td>
                <td class="ratio{% if total_gain > 0 %} up{% elseif (total_gain < 0) %} down{% endif %}">{{ total_gain|number_format(2) }}%</td>
                <td></td>
                <td class="money{% if total_tenValue > 0 %} up{% elseif (total_tenValue < 0) %} down{% endif %}">{{ total_tenValue|round(2)|number_format(2) }}</td>
                <td></td>
                <td class="money{% if total_targetValue > 0 %} up{% elseif (total_targetValue < 0) %} down{% endif %}">{{ total_targetValue|round(2)|number_format(2) }}</td>
                <td class="text"></td>
                {% if tradeType == 'Long' %}
                    <td></td>
                {% endif %}
            </tr>
            </tfoot>
            {% endif %}
        </table>
    {% endfor %}
{% endblock %}