src/Entity/Trade.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\TradeRepository")
 */
class Trade
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="integer")
     */
    private $quantity;

    /**
     * @ORM\Column(type="float")
     */
    private $price;

    /**
     * @ORM\Column(type="float")
     */
    private $fee;

    /**
     * @ORM\Column(type="float")
     */
    private $total;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $trade_type;

    /**
     * @var \DateTimeInterface
     * @ORM\Column(type="datetime")
     */
    protected $createdAt;

    /**
     * @var \DateTimeInterface
     * @ORM\Column(type="datetime")
     */
    protected $updatedAt;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $description;

    /**
     * @ORM\Column(type="float")
     */
    private $adjusted_price;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $orderType;

    /**
     * @ORM\Column(type="datetime")
     */
    private $executedAt;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Stock", inversedBy="trades")
     */
    private $stock;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getQuantity(): ?int
    {
        return $this->quantity;
    }

    public function setQuantity(int $quantity): self
    {
        $this->quantity = $quantity;

        return $this;
    }

    public function getPrice(): ?float
    {
        return $this->price;
    }

    public function setPrice(float $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getFee(): ?float
    {
        return $this->fee;
    }

    public function setFee(float $fee): self
    {
        $this->fee = $fee;

        return $this;
    }

    public function getTotal(): ?float
    {
        return $this->total;
    }

    public function setTotal(float $total): self
    {
        $this->total = $total;

        return $this;
    }

    public function getTradeType(): ?string
    {
        return $this->trade_type;
    }

    public function setTradeType(string $trade_type): self
    {
        $this->trade_type = $trade_type;

        return $this;
    }

    public function getCreatedAt(): \DateTimeInterface
    {
        return $this->createdAt;
    }

    public function getUpdatedAt(): \DateTimeInterface
    {
        return $this->updatedAt;
    }

    public function setCreatedAt(\DateTimeInterface $createdAt): void
    {
        $this->createdAt = $createdAt;
    }

    public function setUpdatedAt(\DateTimeInterface $updatedAt): void
    {
        $this->updatedAt = $updatedAt;
    }

    /**
     * Updates createdAt and updatedAt timestamps.
     */
    public function updateTimestamps(): void
    {
        // Create a datetime with microseconds
        $dateTime = \DateTime::createFromFormat('U.u', sprintf('%.6F', microtime(true)));

        $dateTime->setTimezone(new \DateTimeZone(date_default_timezone_get()));

        if ($this->createdAt === null) {
            $this->createdAt = $dateTime;
        }

        $this->updatedAt = $dateTime;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getAdjustedPrice(): ?float
    {
        return $this->adjusted_price;
    }

    public function setAdjustedPrice(float $adjusted_price): self
    {
        $this->adjusted_price = $adjusted_price;

        return $this;
    }

    public function getOrderType(): ?string
    {
        return $this->orderType;
    }

    public function setOrderType(string $orderType): self
    {
        $this->orderType = $orderType;

        return $this;
    }

    public function getExecutedAt(): ?\DateTimeInterface
    {
        return $this->executedAt;
    }

    public function setExecutedAt(\DateTimeInterface $executedAt): self
    {
        $this->executedAt = $executedAt;

        return $this;
    }

    public function getStock(): ?Stock
    {
        return $this->stock;
    }

    public function setStock(?Stock $stock): self
    {
        $this->stock = $stock;

        return $this;
    }
}

src/Controller/TransactionController.php
<?php

namespace App\Controller;

use App\Services\TradeManager;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\HttpFoundation\Request;

class TransactionController extends AbstractController {

    public function view(Request $request, TradeManager $tradeManager) {
        $em = $this->getDoctrine()->getManager();

        $transactions = $em->getRepository('App:Transaction')->getAll();

        return $this->render('transaction/view.html.twig', [
            'transactions' => $transactions
        ]);
    }

    public function add(Request $request, TradeManager $tradeManager) {
        $em = $this->getDoctrine()->getManager();
        $transactionRepo = $em->getRepository('App:Transaction');

        $builder = $this->createFormBuilder();
        $builder
            ->add('pastebox', TextareaType::class)
            ->add('submit', SubmitType::class);

        $form = $builder->getForm();

        if ($request->isMethod('post')) {
            $form->handleRequest($request);

            if ($form->isValid()) {
                $raw_data = $form->getData()['pastebox'];

                $records = $transactionRepo->createFromRaw($raw_data);

                foreach ($records as $record) {
                    $em->persist($record);
                }

                $em->flush();

                return $this->redirectToRoute('transaction_main');
            }
        }

        $lastTransactionAdded = $transactionRepo->findOneBy([], [
            'executedAt' => 'DESC'
        ]);

        return $this->render('transaction/add.html.twig', [
            'form' => $form->createView(),
            'lastTransactionAdded' => $lastTransactionAdded
        ]);
    }

}

templates/transaction/add.html.twig
{% extends 'base.html.twig' %}

{% form_theme form 'bootstrap_4_layout.html.twig' %}

{% block extranav %}
{% endblock %}

{% block content %}
    <p>Copy new transactions from the corporate actions tables directly from the Investopedia page, and paste it here.</p>

    {% if lastTransactionAdded %}
        <p>
            Last transaction added: {{ lastTransactionAdded.quantity }}x {{ lastTransactionAdded.stock.symbol }} @ {{ lastTransactionAdded.executedAt|date('Y-m-d h:i:s') }}
        </p>
    {% endif %}

    {{ form(form) }}
{% endblock %}

templates/transaction/view.html.twig
{% extends 'base.html.twig' %}

{% block extranav %}
{% endblock %}

{% block content %}
    <table class="table table-striped trade-data">
        <thead>
        <tr>
            <th>Date</th>
            <th>Trade type</th>
            <th>Symbol</th>
            <th>Quantity</th>
            <th>Price</th>
            <th>Total value</th>
            <th>Account value</th>
        </tr>
        </thead>

        {% set total_value = 0 %}

        <tbody>
        {% for transaction in transactions %}
            {% set total_value = (total_value + (transaction.price *transaction.quantity)) %}

            <tr>
                <td class="text">{{ transaction.executedAt|date('Y-m-d H:i:s') }}</td>
                <td class="text">{{ transaction.tradeType }}</td>
                <td class="text">{% if transaction.stock %}{{ transaction.stock.symbol }}{% endif %}</td>
                <td class="number">{{ transaction.quantity }}</td>
                <td class="money">{{ transaction.price|round(2)|number_format(2) }}</td>
                <td class="money">{{ transaction.totalValue|round(2)|number_format(2) }}</td>
                <td class="money">{{ transaction.accountValue|round(2)|number_format(2) }}</td>
            </tr>
        {% endfor %}
        </tbody>

        <tfoot>
        <tr>
            <td class="text">Totals:</td>
            <td class="text"></td>
            <td class="text"></td>
            <td class="text"></td>
            <td class="text"></td>
            <td class="money">{{ total_value|number_format(2) }}</td>
            <td class="text"></td>
            <td class="text"></td>
            <td class="text"></td>
            <td class="text"></td>
        </tr>
        </tfoot>
    </table>
{% endblock %}